[package]
name = "lightning-persister"
version = "0.0.104"
authors = ["Valentine Wallace", "Matt Corallo"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/lightningdevkit/rust-lightning/"
description = """
Utilities to manage Rust-Lightning channel data persistence and retrieval.
"""

[features]
unstable = ["lightning/unstable"]

[dependencies]
bitcoin = "0.29"
lightning = { version = "0.0.104", path = "../lightning" }
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winbase"] }

[dev-dependencies]
lightning = { version = "0.0.104", path = "../lightning", features = ["_test_utils"] }
